
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Group')
BEGIN

CREATE TABLE [dbo].[Group](
	[Id] [VARCHAR](128) NOT NULL,
	[Code] [nvarchar](200) NULL,
	[Name] [nvarchar](500) NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Vehicle')
BEGIN

CREATE TABLE [dbo].[Vehicle](
	[Id] [VARCHAR](128) NOT NULL,
	[Phone] [varchar](200) NULL,
	[Name] [nvarchar](500) NULL,
	[Plate] [varchar](200) NULL,
	[GroupId] [varchar](200) NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VehicleEvent')
BEGIN

CREATE TABLE [dbo].[VehicleEvent](
	[Id] [VARCHAR](128) NOT NULL,
	[EventCode] [varchar](100) NULL,
	[PlateIn] [varchar](150) NULL,
	[PicVehicleIn] [varchar](max) NULL,
	[PicAllIn] [varchar](max) NULL,
	[GateIn] [varchar](150) NULL,
	[DateTimeIn] [datetime] NOT NULL,
	[PlateOut] [varchar](150) NULL,
	[PicVehicleOut] [varchar](max) NULL,
	[PicAllOut] [varchar](max) NULL,
	[GateOut] [varchar](150) NULL,
	[DateTimeOut] [datetime] NOT NULL,
	[GroupId] [varchar](150) NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[IsDelete] bit NOT NULL default (0),
 CONSTRAINT [PK_VehicleEvent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblCamera' AND COLUMN_NAME = 'MotionZone')
BEGIN
	ALTER TABLE [tblCamera] ADD MotionZone nvarchar(128) NULL DEFAULT NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblCamera' AND COLUMN_NAME = 'Config')
BEGIN
	ALTER TABLE [tblCamera] ADD Config nvarchar(256) NULL DEFAULT NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Vehicle' AND COLUMN_NAME = 'VehicleType')
BEGIN
	ALTER TABLE [Vehicle] ADD VehicleType int NOT NULL DEFAULT 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Vehicle' AND COLUMN_NAME = 'Weight')
BEGIN
	ALTER TABLE [Vehicle] ADD Weight int NOT NULL DEFAULT 0
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'Cost')
BEGIN
	ALTER TABLE [tbl_Event] ADD Cost decimal not null DEFAULT 0
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'ParkingPosition')
BEGIN
	ALTER TABLE [tbl_Event] ADD ParkingPosition varchar(250) null
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'PaymentStatus')
BEGIN
	ALTER TABLE [tbl_Event] ADD PaymentStatus varchar(10) default('0')
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'ServiceCode')
BEGIN
	ALTER TABLE [tbl_Event] ADD ServiceCode varchar(250) null
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'PackageNumber')
BEGIN
	ALTER TABLE [tbl_Event] ADD PackageNumber varchar(250) null
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'Quantity')
BEGIN
	ALTER TABLE [tbl_Event] ADD Quantity varchar(10) null
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'DivisionDate')
BEGIN
	ALTER TABLE [tbl_Event] ADD DivisionDate Datetime not null default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'VehicleStatusVN')
BEGIN
	ALTER TABLE [tbl_Event] ADD VehicleStatusVN int not null default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'VehicleStatusCN')
BEGIN
	ALTER TABLE [tbl_Event] ADD VehicleStatusCN int not null default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'TimeInVN')
BEGIN
	ALTER TABLE [tbl_Event] ADD TimeInVN Datetime not null  default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'TimeOutVN')
BEGIN
	ALTER TABLE [tbl_Event] ADD TimeOutVN Datetime not null  default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'TimeInCN')
BEGIN
	ALTER TABLE [tbl_Event] ADD TimeInCN Datetime not null  default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'TimeOutCN')
BEGIN
	ALTER TABLE [tbl_Event] ADD TimeOutCN Datetime not null  default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tbl_Event' AND COLUMN_NAME = 'ConfirmDate')
BEGIN
	ALTER TABLE [tbl_Event] ADD ConfirmDate Datetime not null  default('2021-01-01 00:00:00.000')
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblGate' AND COLUMN_NAME = 'IsXi')
BEGIN
	ALTER TABLE [tblGate] ADD IsXi bit NOT NULL DEFAULT 0
END


